// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Envelope.ResourcesGenerator
{
    using Envelope.Extensions;
    using Envelope.Generator;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using System.Resources;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ResourcesGenerator : GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	string targetProject = GetParam("TargetProject");
	string nmspace = GetParam("RootNamespace");
	var resFiles = GetParam<List<Envelope.Localization.ResourceFile>>("ResFiles");
	
	foreach (var resFile in resFiles)
	{
		var resStructure = resFile.GetConfigurationFolderStructure(targetProject);
		var resPath = resFile.GetConfigurationFolderPath(null, targetProject);
		StartNewFile(resPath, resFile.Name + "Resources.cs");
		
		int ident = 0;


            
            #line default
            #line hidden
            this.Write(@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Extensions.Localization;
using Envelope.Extensions;
using Envelope.Localization;

namespace ");
            
            #line 41 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nmspace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 43 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

		foreach (var parentClass in resStructure)
		{

            
            #line default
            #line hidden
            
            #line 47 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("public partial class ");
            
            #line 47 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parentClass));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 48 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 49 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

			ident++;
		}
		string className = resFile.Name.ToCammelCase(removeUnderscores: false);
		var baseName = resPath.TrimPrefix(targetProject).Replace(System.IO.Path.DirectorySeparatorChar, '.') + "." + resFile.Name;

            
            #line default
            #line hidden
            
            #line 55 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("public partial class ");
            
            #line 55 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 56 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 57 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("private static Lazy<IStringLocalizer> _stringLocalizer = new Lazy<IStringLocalize" +
                    "r>(() => Resources.Localizers.GetStringLocalizer<Resources.");
            
            #line 57 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write(">());\r\n\r\n");
            
            #line 59 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public static IStringLocalizer StringLocalizer => _stringLocalizer.Value;\r\n\r\n");
            
            #line 61 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public const string __BaseName = \"");
            
            #line 61 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n");
            
            #line 63 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public static class __Keys\r\n");
            
            #line 64 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("{\r\n\r\n");
            
            #line 66 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

				int resCount = 0;
				foreach (var resource in resFile)
				{
					var resName = resource.Name.ToCammelCase(removeUnderscores: false);
					if (string.IsNullOrWhiteSpace(resource.Value))
					{
						throw new InvalidOperationException("Resource " + resFile.FullPath + " has invalid value for name " + resource.Name);
					}

					if (0 < resCount)
					{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 80 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

					}

            
            #line default
            #line hidden
            
            #line 83 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 2)));
            
            #line default
            #line hidden
            this.Write("public const string ");
            
            #line 83 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 83 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resource.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 84 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

					if (0 < resource.NumericParameters.Count)
					{
						foreach (var numParam in resource.NumericParameters)
						{

            
            #line default
            #line hidden
            
            #line 90 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 2)));
            
            #line default
            #line hidden
            this.Write("public const string ");
            
            #line 90 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            this.Write("_p");
            
            #line 90 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(numParam.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 90 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(numParam));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 91 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

						}
					}

					if (0 < resource.StringParameters.Count)
					{
						foreach (var strParam in resource.StringParameters)
						{

            
            #line default
            #line hidden
            
            #line 100 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 2)));
            
            #line default
            #line hidden
            this.Write("public const string ");
            
            #line 100 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            this.Write("_p_");
            
            #line 100 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strParam.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 100 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strParam));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 101 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

						}
					}
					resCount++;
				}

            
            #line default
            #line hidden
            
            #line 107 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 108 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

		
				foreach (var resource in resFile)
				{
					var resName = resource.Name.ToCammelCase(removeUnderscores: false);
					var withParams = (0 < resource.NumericParameters.Count || 0 < resource.StringParameters.Count)
						? "__WithParams"
						: "";

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 118 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public static string ");
            
            #line 118 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            
            #line 118 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(withParams));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 119 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\t=> StringLocalizer[Resources.");
            
            #line 119 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write(".__Keys.");
            
            #line 119 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            this.Write("]!;\r\n");
            
            #line 120 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"


					if (0 < resource.NumericParameters.Count)
					{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 126 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public static string ");
            
            #line 126 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            this.Write("(object ");
            
            #line 126 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", object ", resource.NumericParameters.Select(x => x.ToCammelCase(removeUnderscores: false).FirstToLower()))));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 127 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 128 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\tstring res = StringLocalizer[Resources.");
            
            #line 128 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write(".__Keys.");
            
            #line 128 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            this.Write("]!;\r\n");
            
            #line 129 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\treturn res.ReplacePlaceholders(new Dictionary<string, object>\r\n");
            
            #line 130 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\t\t{\r\n");
            
            #line 131 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

						foreach (var numParam in resource.NumericParameters)
						{

            
            #line default
            #line hidden
            
            #line 135 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\t\t\t{ Resources.");
            
            #line 135 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write(".__Keys.");
            
            #line 135 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            this.Write("_p");
            
            #line 135 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(numParam.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 135 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(numParam.ToCammelCase(removeUnderscores: false).FirstToLower()));
            
            #line default
            #line hidden
            this.Write(" },\r\n");
            
            #line 136 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

						}

            
            #line default
            #line hidden
            
            #line 139 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\t\t});\r\n");
            
            #line 140 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 141 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

					}

					if (0 < resource.StringParameters.Count)
					{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 148 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("public static string ");
            
            #line 148 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            this.Write("(object ");
            
            #line 148 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", object ", resource.StringParameters.Select(x => x.ToCammelCase(removeUnderscores: false).FirstToLower()))));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 149 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 150 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\tstring res = StringLocalizer[Resources.");
            
            #line 150 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write(".__Keys.");
            
            #line 150 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            this.Write("]!;\r\n");
            
            #line 151 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\treturn res.ReplacePlaceholders(new Dictionary<string, object>\r\n");
            
            #line 152 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\t\t{\r\n");
            
            #line 153 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

						foreach (var strParam in resource.StringParameters)
						{

            
            #line default
            #line hidden
            
            #line 157 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\t\t\t{ Resources.");
            
            #line 157 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseName));
            
            #line default
            #line hidden
            this.Write(".__Keys.");
            
            #line 157 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resName));
            
            #line default
            #line hidden
            this.Write("_p_");
            
            #line 157 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strParam.ToCammelCase(removeUnderscores: false)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 157 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(strParam.ToCammelCase(removeUnderscores: false).FirstToLower()));
            
            #line default
            #line hidden
            this.Write(" },\r\n");
            
            #line 158 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

						}

            
            #line default
            #line hidden
            
            #line 161 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("\t\t});\r\n");
            
            #line 162 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident + 1)));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 163 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

					}
					resCount++;
				}

            
            #line default
            #line hidden
            
            #line 168 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            
            #line 170 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("public partial class ");
            
            #line 170 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("LocalizerFactory : ResourceLocalizer<");
            
            #line 170 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resPath.TrimPrefix(targetProject).Replace(System.IO.Path.DirectorySeparatorChar, '.')));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 170 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resFile.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 171 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 172 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 172 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("LocalizerFactory(IServiceProvider serviceProvider)\r\n");
            
            #line 173 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("\t\t: base(serviceProvider,\r\n");
            
            #line 174 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 174 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(".__BaseName,\r\n");
            
            #line 175 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("\t\t\tnew System.Reflection.AssemblyName(typeof(");
            
            #line 175 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("LocalizerFactory).Assembly.FullName!).Name!)\r\n");
            
            #line 176 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("\t{\r\n");
            
            #line 177 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("\t}\r\n");
            
            #line 178 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(ident)));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 179 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"


		for (int i = resStructure.Count - 1; 0 <= i; i--)
		{

            
            #line default
            #line hidden
            
            #line 184 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetIdent(i)));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 185 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

		}
	}
	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 190 "C:\Code\GitLab\En_GitHub\envelope-resourcesgenerator\src\Envelope.ResourcesGenerator\ResourcesGenerator.tt"

	private string GetIdent(int count)
	{
		return GetIdent(null, count);
	}

	private string GetIdent(string baseIdent, int count)
	{
		StringBuilder sb = new StringBuilder(baseIdent ?? "");
		for (int i = 0; i < count; i++)
		{
			sb.Append("\t");
		}
		return sb.ToString();
	}

	private IEnumerable<string> Lines(string value)
	{
		return value.Split(new[] { Environment.NewLine }, StringSplitOptions.None);
	}

	private string Xml(string value)
	{
		return value.Replace("<", "&lt;").Replace(">", "&gt;");
	}

	private string List(IEnumerable<string> items)
	{
		return List(null, items);
	}

	private string List(string prefix, IEnumerable<string> items, string suffix = null)
	{
		return string.Join(", ", items.Select(i => prefix + i + suffix));
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
